services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - db
    networks:
      - bo-bank-network

  # Nginx Service
  web:
    image: nginx:latest
    restart: on-failure
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - bo-bank-network

  # PostgreSQL Service
  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bo-bank-network

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - bo-bank-network

  # Redis Service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - bo-bank-network

networks:
  bo-bank-network:
    driver: bridge

volumes:
  db-data:
